### ISSUE TITLE
how to add selfhosted domains with non-standard ports to blacklist?

### ISSUE THREAD

**Issue by rezad1393** [ivysrono/iWebExtension#2]
like this domain https://test:1000/index.html

**Comment by ivysrono** [comment]
![图片](https://user-images.githubusercontent.com/2649544/77912715-9ad51100-72c5-11ea-9a82-283cd7a2a52c.png)
Test? Result?

**Comment by rezad1393** [comment]
sorry.
it may be on my end.
I have installed freshrss (https://github.com/FreshRSS/FreshRSS) and a feed that is http and has pictures loaded from http domain fails to load the images.
and it was not your addon's fault.
I disabled your addon and I get this error:

Content Security Policy: Upgrading insecure request ‘http://img187.imagevenue.com/----’ to use ‘https’

and the loading fail because that site doesnt support https.
so it is freshrss fault.

**Comment by ivysrono** [comment]
Ok.
